import http from 'node:http';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { createHash, pbkdf2Sync, randomBytes, timingSafeEqual } from 'node:crypto';
import { extname, join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

const root = process.cwd();
try {
  const envFile = await readFile(join(root, '.env'), 'utf8');
  for (const line of envFile.split(/\r?\n/)) {
    const match = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*?)\s*$/);
    if (match && !process.env[match[1]]) process.env[match[1]] = match[2].replace(/^['"]|['"]$/g, '');
  }
} catch { /* .env is optional; platform environment variables take priority. */ }
const port = Number(process.env.PORT || 3000);
const databaseDirectory = join(root, 'data');
await mkdir(databaseDirectory, { recursive: true });
await mkdir(join(root, 'uploads'), { recursive: true });
const db = new DatabaseSync(process.env.DATABASE_PATH || join(databaseDirectory, 'sports-world.db'));
db.exec('PRAGMA foreign_keys = ON;');

const config = {
  shopName: 'Sports World', shopAddress: 'Gate Road, Pattaya',
  ownerPhone: process.env.OWNER_PHONE_NUMBER || '',
  instagramHandle: process.env.SHOP_INSTAGRAM_HANDLE || '',
  logo: '/assets/sports-world-logo-source.png', shopImage: '/assets/sports-world-storefront.png'
};
const json = (response, status, value) => response.writeHead(status, { 'Content-Type': 'application/json; charset=utf-8' }).end(JSON.stringify(value));
const error = (response, status, message) => json(response, status, { error: message });
const now = () => new Date().toISOString();
const id = () => randomBytes(16).toString('hex');
const hashPassword = password => { const salt = randomBytes(16).toString('hex'); return `${salt}:${pbkdf2Sync(password, salt, 310000, 32, 'sha256').toString('hex')}`; };
const checkPassword = (password, saved) => { const [salt, digest] = String(saved).split(':');if(!/^[a-f0-9]{32}$/.test(salt||'')||!/^[a-f0-9]{64}$/.test(digest||'')||String(password).length>1024)return false;const candidate=pbkdf2Sync(password,salt,310000,32,'sha256').toString('hex');return timingSafeEqual(Buffer.from(digest,'hex'),Buffer.from(candidate,'hex')); };
const one = (sql, ...params) => db.prepare(sql).get(...params);
const all = (sql, ...params) => db.prepare(sql).all(...params);
const run = (sql, ...params) => db.prepare(sql).run(...params);

db.exec(`
CREATE TABLE IF NOT EXISTS users (id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT NOT NULL UNIQUE, password_hash TEXT NOT NULL, role TEXT NOT NULL DEFAULT 'customer' CHECK(role IN ('customer','admin','superadmin')), active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS categories (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE, kind TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, name TEXT NOT NULL, category_id TEXT REFERENCES categories(id), type TEXT NOT NULL, description TEXT NOT NULL, price_cents INTEGER NOT NULL, discount_cents INTEGER, stock INTEGER NOT NULL DEFAULT 0, sku TEXT NOT NULL UNIQUE, brand TEXT, image TEXT, status TEXT NOT NULL DEFAULT 'active', metadata TEXT NOT NULL DEFAULT '{}', demo INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_photos (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, url TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS store_photos (id TEXT PRIMARY KEY, url TEXT NOT NULL, placement TEXT NOT NULL CHECK(placement IN ('hero','gallery')), caption TEXT NOT NULL DEFAULT '', admin_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS product_variants (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, label TEXT NOT NULL, value TEXT NOT NULL, stock INTEGER NOT NULL DEFAULT 0, price_adjustment_cents INTEGER NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS stock_transactions (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), previous_stock INTEGER NOT NULL, change_amount INTEGER NOT NULL, new_stock INTEGER NOT NULL, reason TEXT NOT NULL, admin_id TEXT NOT NULL REFERENCES users(id), created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS carts (id TEXT PRIMARY KEY, user_id TEXT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS cart_items (id TEXT PRIMARY KEY, cart_id TEXT NOT NULL REFERENCES carts(id) ON DELETE CASCADE, product_id TEXT REFERENCES products(id), quantity INTEGER NOT NULL, customization_id TEXT, unit_price_cents INTEGER NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS orders (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), status TEXT NOT NULL, subtotal_cents INTEGER NOT NULL, discount_cents INTEGER NOT NULL DEFAULT 0, total_cents INTEGER NOT NULL, coupon_code TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id TEXT, product_name TEXT NOT NULL, quantity INTEGER NOT NULL, unit_price_cents INTEGER NOT NULL, customization_snapshot TEXT, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS countries (id TEXT PRIMARY KEY, name TEXT NOT NULL UNIQUE);
CREATE TABLE IF NOT EXISTS teams (id TEXT PRIMARY KEY, name TEXT NOT NULL, country_id TEXT REFERENCES countries(id), sport TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS players (id TEXT PRIMARY KEY, name TEXT NOT NULL, team_id TEXT REFERENCES teams(id));
CREATE TABLE IF NOT EXISTS jerseys (id TEXT PRIMARY KEY, product_id TEXT NOT NULL UNIQUE REFERENCES products(id) ON DELETE CASCADE, sport TEXT NOT NULL, team_id TEXT REFERENCES teams(id), country_id TEXT REFERENCES countries(id), player_id TEXT REFERENCES players(id), season TEXT, tournament TEXT, jersey_type TEXT);
CREATE TABLE IF NOT EXISTS customization_templates (id TEXT PRIMARY KEY, name TEXT NOT NULL, product_type TEXT NOT NULL, base_price_cents INTEGER NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, config TEXT NOT NULL DEFAULT '{}');
CREATE TABLE IF NOT EXISTS customization_designs (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), template_id TEXT REFERENCES customization_templates(id), name TEXT NOT NULL, front_design TEXT NOT NULL, back_design TEXT NOT NULL, preview TEXT, price_cents INTEGER NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS wishlists (id TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, product_id TEXT NOT NULL REFERENCES products(id) ON DELETE CASCADE, created_at TEXT NOT NULL, UNIQUE(user_id, product_id));
CREATE TABLE IF NOT EXISTS coupons (id TEXT PRIMARY KEY, code TEXT NOT NULL UNIQUE, type TEXT NOT NULL CHECK(type IN ('percent','fixed')), value INTEGER NOT NULL, minimum_cents INTEGER NOT NULL DEFAULT 0, starts_at TEXT, ends_at TEXT, uses_remaining INTEGER, active INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS password_resets (token_hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id), expires_at TEXT NOT NULL);
`);

function seed() {
  if (one('SELECT id FROM products LIMIT 1')) return;
  const categories = [['Cricket','equipment'],['Football','equipment'],['Basketball','equipment'],['Badminton','equipment'],['Tennis','equipment'],['Table Tennis','equipment'],['Volleyball','equipment'],['Gym & Fitness','equipment'],['Other Sports','equipment'],['Football Jerseys','merchandise'],['Cricket Jerseys','merchandise'],['Sports T-shirts','merchandise'],['Shorts','merchandise'],['Tracksuits','merchandise'],['Caps','merchandise'],['Socks','merchandise']];
  const categoryIds = {};
  for (const [name, kind] of categories) { run('INSERT OR IGNORE INTO categories VALUES (?,?,?,?)', id(), name, kind, now()); categoryIds[name] = one('SELECT id FROM categories WHERE name=?', name).id; }
  const products = [
    ['Cricket Bat Starter','Cricket','equipment','Balanced English-willow style practice bat for training.','249900',12,'SW-CR-001','Sports World','/assets/sports-world-sign.png'],
    ['Match Football','Football','equipment','Durable stitched football for everyday training and matches.','89900',18,'SW-FB-001','Sports World','/assets/sports-world-sign.png'],
    ['Badminton Racket','Badminton','equipment','Lightweight racket for club and recreational play.','119900',7,'SW-BD-001','Sports World','/assets/sports-world-sign.png'],
    ['Custom Team Jersey','Football Jerseys','merchandise','Made-to-order jersey with your name and number.','79900',20,'SW-JR-001','Sports World','/assets/sports-world-logo-source.png'],
    ['Training T-shirt','Sports T-shirts','merchandise','Breathable training t-shirt. Available in selected sizes.','49900',15,'SW-TS-001','Sports World','/assets/sports-world-logo-source.png']
  ];
  for (const [name, category, type, description, price, stock, sku, brand, image] of products) { const productId=id(); run('INSERT INTO products VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',productId,name,categoryIds[category],type,description,Number(price),null,stock,sku,brand,image,'active','{}',1,now(),now()); }
  const templateId = id(); run('INSERT INTO customization_templates VALUES (?,?,?,?,?,?)', templateId, 'Classic Sports Jersey', 'jersey', 79900, 1, JSON.stringify({ printNameCents: 10000, printNumberCents: 10000, extraLogoCents: 15000 }));
}
seed();
if (process.env.FIRST_SUPERADMIN_EMAIL && process.env.FIRST_SUPERADMIN_PASSWORD && !one("SELECT id FROM users WHERE role='superadmin'")) run('INSERT INTO users VALUES (?,?,?,?,?,?,?)', id(), 'Store Owner', process.env.FIRST_SUPERADMIN_EMAIL.toLowerCase(), hashPassword(process.env.FIRST_SUPERADMIN_PASSWORD), 'superadmin', 1, now());

async function body(request, limit = 6_000_000) { const chunks=[];let size=0;for await(const chunk of request){size+=chunk.length;if(size>limit)throw Object.assign(new Error('Request is too large.'),{status:413});chunks.push(chunk);}try{return chunks.length?JSON.parse(Buffer.concat(chunks).toString('utf8')):{};}catch{throw Object.assign(new Error('Invalid JSON.'),{status:400});} }
function cookie(request, name) { return (request.headers.cookie || '').split(';').map(v=>v.trim()).find(v=>v.startsWith(`${name}=`))?.slice(name.length+1); }
function currentUser(request) { const token=cookie(request,'sw_session'); if (!token) return null; const session=one('SELECT s.*,u.name,u.email,u.role,u.active FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=? AND s.expires_at>?',createHash('sha256').update(token).digest('hex'),now()); return session?.active ? { id:session.user_id,name:session.name,email:session.email,role:session.role } : null; }
function requireUser(request,response, roles) { const user=currentUser(request); if(!user) { error(response,401,'Please log in to continue.'); return null; } if(roles && !roles.includes(user.role)) { error(response,403,'You do not have permission for this action.'); return null; } return user; }
function productRows(where='', params=[]) { return all(`SELECT p.*,c.name category FROM products p LEFT JOIN categories c ON c.id=p.category_id ${where} ORDER BY p.created_at DESC`,...params).map(p=>({...p, metadata:JSON.parse(p.metadata), photos:all('SELECT url FROM product_photos WHERE product_id=? ORDER BY created_at',p.id).map(photo=>photo.url)})); }
function cartFor(user) { let cart=one('SELECT * FROM carts WHERE user_id=?',user.id); if(!cart){ cart={id:id(),user_id:user.id,created_at:now(),updated_at:now()}; run('INSERT INTO carts VALUES (?,?,?,?)',cart.id,cart.user_id,cart.created_at,cart.updated_at); } const items=all('SELECT ci.*,p.name,p.stock,p.status,p.image FROM cart_items ci LEFT JOIN products p ON p.id=ci.product_id WHERE ci.cart_id=?',cart.id).map(x=>({...x,snapshot:JSON.parse(x.snapshot)})); return {...cart,items}; }
function money(value) { const number=Number(value); if(!Number.isInteger(number) || number<0) throw new Error('Invalid price.'); return number; }
function normalizeProduct(data) { if(!data.name?.trim() || !data.sku?.trim() || !data.categoryId || !data.description?.trim()) throw new Error('Name, SKU, category, and description are required.'); return {name:data.name.trim(),sku:data.sku.trim().toUpperCase(),categoryId:data.categoryId,type:data.type==='merchandise'?'merchandise':'equipment',description:data.description.trim(),price:money(data.priceCents),discount:data.discountCents===''||data.discountCents==null?null:money(data.discountCents),stock:Number(data.stock),brand:String(data.brand||'').trim(),image:String(data.image||'').trim(),metadata:JSON.stringify(data.metadata||{})}; }
function createSession(response,userId){ const token=randomBytes(32).toString('hex'); const expires=new Date(Date.now()+1000*60*60*24*14).toISOString(); run('INSERT INTO sessions VALUES (?,?,?)',createHash('sha256').update(token).digest('hex'),userId,expires); const secure=process.env.NODE_ENV==='production'?'; Secure':''; response.setHeader('Set-Cookie',`sw_session=${token}; HttpOnly; SameSite=Lax; Path=/; Max-Age=1209600${secure}`); }
function productSearch(q) { const query=`%${q}%`; return productRows("WHERE p.status='active' AND (p.name LIKE ? OR p.description LIKE ? OR p.sku LIKE ? OR c.name LIKE ?)",[query,query,query,query]); }

const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp'};
const publicFiles = new Set(['/','/index.html','/styles.css','/features.css','/script.js','/assets/sports-world-logo-source.png','/assets/sports-world-storefront.png','/assets/sports-world-sign.png','/assets/sports-world-logo.svg']);
async function serveFile(response, pathname) { let relative;if(publicFiles.has(pathname))relative=pathname==='/'?'index.html':pathname.slice(1);else if(/^\/uploads\/[a-f0-9]{32}\.(?:png|jpg|webp)$/.test(pathname))relative=pathname.slice(1);else return error(response,404,'Not found');try{const file=await readFile(join(root,relative));const type=mime[extname(relative).toLowerCase()];if(!type)return error(response,404,'Not found');response.writeHead(200,{'Content-Type':type,'X-Content-Type-Options':'nosniff','Cache-Control':relative.startsWith('assets/')?'public, max-age=86400':'no-cache'}).end(file);}catch{error(response,404,'Not found');} }

const authAttempts=new Map();
function rateLimit(request,response,key,limit,windowMs){const nowMs=Date.now(),ip=String(request.headers['x-forwarded-for']||request.socket.remoteAddress||'unknown').split(',')[0].trim();const bucketKey=`${key}:${ip}`;let bucket=authAttempts.get(bucketKey);if(!bucket||bucket.until<=nowMs)bucket={count:0,until:nowMs+windowMs};bucket.count++;authAttempts.set(bucketKey,bucket);if(authAttempts.size>5000)for(const [k,v]of authAttempts)if(v.until<=nowMs)authAttempts.delete(k);if(bucket.count>limit){response.setHeader('Retry-After',String(Math.ceil((bucket.until-nowMs)/1000)));error(response,429,'Too many attempts. Please try again later.');return false;}return true;}

const server=http.createServer(async(request,response)=>{ response.setHeader('Cache-Control','no-store');response.setHeader('X-Content-Type-Options','nosniff');response.setHeader('X-Frame-Options','DENY');response.setHeader('Referrer-Policy','strict-origin-when-cross-origin');response.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');response.setHeader('Cross-Origin-Opener-Policy','same-origin');response.setHeader('Content-Security-Policy',"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob:; connect-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'");if(process.env.NODE_ENV==='production')response.setHeader('Strict-Transport-Security','max-age=31536000; includeSubDomains');const url=new URL(request.url,`http://${request.headers.host||'localhost'}`); const path=url.pathname; try {
  if(path.startsWith('/api/')&&!['GET','HEAD','OPTIONS'].includes(request.method)){const origin=request.headers.origin;const expectedOrigin=(process.env.NODE_ENV==='production'?'https':'http')+'://'+request.headers.host;if(!origin||new URL(origin).origin!==expectedOrigin)return error(response,403,'Request origin was not accepted.');}
  if((path==='/api/auth/login'||path==='/api/auth/register'||path==='/api/setup')&&request.method==='POST'&&!rateLimit(request,response,path,path==='/api/auth/login'?10:5,15*60*1000))return;
  if(path==='/api/admin/upload'&&request.method==='POST'&&!rateLimit(request,response,path,20,60*60*1000))return;
  if(path==='/api/config' && request.method==='GET') { const hero=one("SELECT url FROM store_photos WHERE placement='hero' ORDER BY created_at DESC LIMIT 1");const gallery=all("SELECT id,url,caption FROM store_photos WHERE placement='gallery' ORDER BY created_at DESC");return json(response,200,{...config,shopImage:hero?.url||config.shopImage,shopGallery:gallery}); }
  if(path==='/api/setup' && request.method==='GET') return json(response,200,{needed:!one("SELECT id FROM users WHERE role='superadmin'")});
  if(path==='/api/store-photos' && request.method==='GET') return json(response,200,all('SELECT id,url,placement,caption,created_at FROM store_photos ORDER BY created_at DESC'));
  if(path==='/api/categories' && request.method==='GET') return json(response,200,all('SELECT * FROM categories ORDER BY kind,name'));
  if(path==='/api/products' && request.method==='GET') { const q=url.searchParams.get('q')||''; const category=url.searchParams.get('category'); const type=url.searchParams.get('type'); let where="WHERE p.status='active'",params=[]; if(q){where+=' AND (p.name LIKE ? OR p.description LIKE ? OR p.sku LIKE ? OR c.name LIKE ?)';params.push(`%${q}%`,`%${q}%`,`%${q}%`,`%${q}%`);} if(category){where+=' AND c.name=?';params.push(category);}if(type){where+=' AND p.type=?';params.push(type);} const sort=url.searchParams.get('sort'); const rows=productRows(where,params); rows.sort((a,b)=>sort==='price_asc'?a.price_cents-b.price_cents:sort==='price_desc'?b.price_cents-a.price_cents:a.name.localeCompare(b.name)); return json(response,200,rows); }
  if(path==='/api/search' && request.method==='GET') return json(response,200,productSearch(url.searchParams.get('q')||'').slice(0,8));
  if(path==='/api/customization-templates' && request.method==='GET') return json(response,200,all('SELECT id,name,product_type,base_price_cents,config FROM customization_templates WHERE enabled=1'));
  if(path==='/api/me' && request.method==='GET') return json(response,200,{user:currentUser(request)});
  if(path==='/api/setup' && request.method==='POST') { if(one("SELECT id FROM users WHERE role='superadmin'")) return error(response,403,'A super admin already exists.'); const data=await body(request); if(!data.name?.trim()||!/^\S+@\S+\.\S+$/.test(data.email||'')||String(data.password||'').length<10||String(data.password||'').length>1024) return error(response,400,'Enter a name, valid email, and a password of at least 10 characters.'); const userId=id();run('INSERT INTO users VALUES (?,?,?,?,?,?,?)',userId,data.name.trim(),data.email.trim().toLowerCase(),hashPassword(data.password),'superadmin',1,now());createSession(response,userId);return json(response,201,{user:{id:userId,name:data.name.trim(),email:data.email.trim(),role:'superadmin'}}); }
  if(path==='/api/auth/register' && request.method==='POST') { const data=await body(request); if(!data.name?.trim()||!/^\S+@\S+\.\S+$/.test(data.email||'')||String(data.password||'').length<10||String(data.password||'').length>1024||String(data.password||'').length>1024) return error(response,400,'Enter a name, valid email, and a password of 10 to 1024 characters.'); const userId=id();try{run('INSERT INTO users VALUES (?,?,?,?,?,?,?)',userId,data.name.trim().slice(0,120),data.email.trim().toLowerCase(),hashPassword(data.password),'customer',1,now());}catch{return error(response,409,'An account with that email already exists.');}createSession(response,userId);return json(response,201,{user:{id:userId,name:data.name.trim(),email:data.email.trim(),role:'customer'}}); }
  if(path==='/api/auth/login' && request.method==='POST') { const data=await body(request);const user=one('SELECT * FROM users WHERE email=?',String(data.email||'').trim().toLowerCase());if(!user||!checkPassword(String(data.password||''),user.password_hash))return error(response,401,'Incorrect email or password.');if(!user.active)return error(response,403,'This account has been disabled.');createSession(response,user.id);return json(response,200,{user:{id:user.id,name:user.name,email:user.email,role:user.role}}); }
  if(path==='/api/auth/logout' && request.method==='POST') { const token=cookie(request,'sw_session');if(token)run('DELETE FROM sessions WHERE token_hash=?',createHash('sha256').update(token).digest('hex'));response.setHeader('Set-Cookie','sw_session=; HttpOnly; Path=/; Max-Age=0');return json(response,200,{ok:true}); }
  if(path==='/api/cart' && request.method==='GET'){const user=requireUser(request,response);if(user)return json(response,200,cartFor(user));return;}
  if(path==='/api/cart/items' && request.method==='POST'){const user=requireUser(request,response);if(!user)return;const data=await body(request);const product=one("SELECT * FROM products WHERE id=? AND status='active'",data.productId);const quantity=Number(data.quantity||1);if(!product)return error(response,404,'Product unavailable.');if(!Number.isInteger(quantity)||quantity<1||quantity>product.stock)return error(response,400,'Requested quantity is unavailable.');const cart=cartFor(user);const existing=one('SELECT * FROM cart_items WHERE cart_id=? AND product_id=? AND customization_id IS NULL',cart.id,product.id);if(existing){if(existing.quantity+quantity>product.stock)return error(response,400,'Requested quantity is unavailable.');run('UPDATE cart_items SET quantity=? WHERE id=?',existing.quantity+quantity,existing.id);}else run('INSERT INTO cart_items VALUES (?,?,?,?,?,?,?)',id(),cart.id,product.id,quantity,null,product.discount_cents??product.price_cents,JSON.stringify({name:product.name,image:product.image,sku:product.sku}));run('UPDATE carts SET updated_at=? WHERE id=?',now(),cart.id);return json(response,201,cartFor(user));}
  if(path.match(/^\/api\/cart\/items\/[a-f0-9]+$/) && request.method==='PATCH'){const user=requireUser(request,response);if(!user)return;const data=await body(request);const cart=cartFor(user);const item=one('SELECT ci.*,p.stock FROM cart_items ci LEFT JOIN products p ON p.id=ci.product_id WHERE ci.id=? AND ci.cart_id=?',path.split('/').pop(),cart.id);if(!item)return error(response,404,'Cart item not found.');const quantity=Number(data.quantity);if(!Number.isInteger(quantity)||quantity<1||quantity>item.stock)return error(response,400,'Requested quantity is unavailable.');run('UPDATE cart_items SET quantity=? WHERE id=?',quantity,item.id);return json(response,200,cartFor(user));}
  if(path.match(/^\/api\/cart\/items\/[a-f0-9]+$/) && request.method==='DELETE'){const user=requireUser(request,response);if(!user)return;const cart=cartFor(user);run('DELETE FROM cart_items WHERE id=? AND cart_id=?',path.split('/').pop(),cart.id);return json(response,200,cartFor(user));}
  if(path==='/api/designs' && request.method==='POST'){const user=requireUser(request,response);if(!user)return;const data=await body(request);if(!data.templateId||!Array.isArray(data.frontDesign)||!Array.isArray(data.backDesign)||data.frontDesign.length>30||data.backDesign.length>30)return error(response,400,'A valid front and back design is required.');const template=one('SELECT * FROM customization_templates WHERE id=? AND enabled=1',data.templateId);if(!template)return error(response,404,'Design template unavailable.');const name=String(data.name||'My custom jersey').slice(0,80),designId=id(),price=template.base_price_cents,category=one("SELECT id FROM categories WHERE name='Football Jerseys'");run('INSERT INTO customization_designs VALUES (?,?,?,?,?,?,?,?,?)',designId,user.id,template.id,name,JSON.stringify(data.frontDesign),JSON.stringify(data.backDesign),null,price,now());const productId=id();run('INSERT INTO products VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',productId,`Custom jersey — ${name.slice(0,55)}`,category?.id,'merchandise','Customer-created custom jersey.',price,null,1,`CUSTOM-${designId.slice(0,8).toUpperCase()}`,'Sports World','/assets/sports-world-logo-source.png','active',JSON.stringify({customizationId:designId,size:['S','M','L','XL','XXL'].includes(data.size)?data.size:'M'}),0,now(),now());return json(response,201,{id:designId,productId});}
  if(path==='/api/orders' && request.method==='POST'){const user=requireUser(request,response);if(!user)return;const data=await body(request);const cart=cartFor(user);if(!cart.items.length)return error(response,400,'Your cart is empty.');db.exec('BEGIN IMMEDIATE');try{let subtotal=0;for(const item of cart.items){const product=one('SELECT * FROM products WHERE id=?',item.product_id);if(!product||product.status!=='active'||product.stock<item.quantity)throw new Error(`${item.snapshot.name} no longer has enough stock.`);subtotal+=item.unit_price_cents*item.quantity;}let discount=0,coupon=null;if(data.couponCode){coupon=one('SELECT * FROM coupons WHERE code=? AND active=1 AND (starts_at IS NULL OR starts_at<=?) AND (ends_at IS NULL OR ends_at>=?)',String(data.couponCode).trim().toUpperCase(),now(),now());if(!coupon)throw new Error('Coupon is invalid or expired.');if(subtotal<coupon.minimum_cents)throw new Error('Cart total does not meet this coupon minimum.');discount=coupon.type==='percent'?Math.floor(subtotal*coupon.value/100):coupon.value;discount=Math.min(discount,subtotal);if(coupon.uses_remaining!==null&&coupon.uses_remaining<1)throw new Error('Coupon has no uses remaining.');}const orderId=id();run('INSERT INTO orders VALUES (?,?,?,?,?,?,?,?,?)',orderId,user.id,'Pending',subtotal,discount,subtotal-discount,coupon?.code||null,now(),now());for(const item of cart.items){const product=one('SELECT * FROM products WHERE id=?',item.product_id);run('INSERT INTO order_items VALUES (?,?,?,?,?,?,?,?)',id(),orderId,product.id,product.name,item.quantity,item.unit_price_cents,item.customization_id||null,item.snapshot);run('UPDATE products SET stock=stock-?,updated_at=? WHERE id=?',item.quantity,now(),product.id);run('INSERT INTO stock_transactions VALUES (?,?,?,?,?,?,?,?)',id(),product.id,product.stock,-item.quantity,product.stock-item.quantity,'Order '+orderId,user.id,now());}if(coupon&&coupon.uses_remaining!==null)run('UPDATE coupons SET uses_remaining=uses_remaining-1 WHERE id=?',coupon.id);run('DELETE FROM cart_items WHERE cart_id=?',cart.id);db.exec('COMMIT');return json(response,201,{id:orderId,status:'Pending'});}catch(e){db.exec('ROLLBACK');return error(response,400,e.message);}}
  if(path==='/api/orders' && request.method==='GET'){const user=requireUser(request,response);if(!user)return;const query=user.role==='customer'?'WHERE o.user_id=?':'';const records=all(`SELECT o.*,u.name customer_name FROM orders o JOIN users u ON u.id=o.user_id ${query} ORDER BY o.created_at DESC`,...(query?[user.id]:[]));return json(response,200,records);}
  if(path==='/api/admin/dashboard' && request.method==='GET'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;return json(response,200,{products:one('SELECT COUNT(*) count FROM products').count,totalStock:one('SELECT COALESCE(SUM(stock),0) count FROM products').count,lowStock:one('SELECT COUNT(*) count FROM products WHERE stock BETWEEN 1 AND 5').count,outOfStock:one('SELECT COUNT(*) count FROM products WHERE stock=0').count,orders:one('SELECT COUNT(*) count FROM orders').count,customers:one("SELECT COUNT(*) count FROM users WHERE role='customer'").count,revenue:one("SELECT COALESCE(SUM(total_cents),0) count FROM orders WHERE status NOT IN ('Cancelled')").count});}
  if(path==='/api/admin/products' && request.method==='GET'){const user=requireUser(request,response,['admin','superadmin']);if(user)return json(response,200,productRows());return;}
  if(path==='/api/admin/products' && request.method==='POST'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;const data=await body(request);const p=normalizeProduct(data);if(!Number.isInteger(p.stock)||p.stock<0)return error(response,400,'Stock must be a whole number.');const productId=id();try{db.exec('BEGIN IMMEDIATE');run('INSERT INTO products VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)',productId,p.name,p.categoryId,p.type,p.description,p.price,p.discount,p.stock,p.sku,p.brand,p.image,'active',p.metadata,0,now(),now());for(const url of (Array.isArray(data.photos)?data.photos:[]).slice(0,8))run('INSERT INTO product_photos VALUES (?,?,?,?)',id(),productId,String(url),now());if(p.stock)run('INSERT INTO stock_transactions VALUES (?,?,?,?,?,?,?,?)',id(),productId,0,p.stock,p.stock,'New product',user.id,now());db.exec('COMMIT');return json(response,201,{id:productId});}catch(e){db.exec('ROLLBACK');return error(response,409,'Product could not be saved. Check that the SKU is unique.');}}
  if(path.match(/^\/api\/admin\/products\/[a-f0-9]+$/) && request.method==='PATCH'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;const productId=path.split('/').pop();const existing=one('SELECT * FROM products WHERE id=?',productId);if(!existing)return error(response,404,'Product not found.');const data=await body(request);const p=normalizeProduct({...existing,...data,categoryId:data.categoryId??existing.category_id,priceCents:data.priceCents??existing.price_cents,discountCents:data.discountCents??existing.discount_cents,stock:data.stock??existing.stock});if(!Number.isInteger(p.stock)||p.stock<0)return error(response,400,'Stock must be a whole number.');try{run('UPDATE products SET name=?,category_id=?,type=?,description=?,price_cents=?,discount_cents=?,stock=?,sku=?,brand=?,image=?,metadata=?,updated_at=? WHERE id=?',p.name,p.categoryId,p.type,p.description,p.price,p.discount,p.stock,p.sku,p.brand,p.image,p.metadata,now(),productId);if(p.stock!==existing.stock)run('INSERT INTO stock_transactions VALUES (?,?,?,?,?,?,?,?)',id(),productId,existing.stock,p.stock-existing.stock,p.stock,String(data.stockReason||'Stock adjustment'),user.id,now());return json(response,200,{id:productId});}catch{return error(response,409,'That SKU already exists.');}}
  if(path.match(/^\/api\/admin\/products\/[a-f0-9]+$/) && request.method==='DELETE'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;run("UPDATE products SET status='archived',updated_at=? WHERE id=?",now(),path.split('/').pop());return json(response,200,{ok:true});}
  if(path==='/api/admin/stock-history' && request.method==='GET'){const user=requireUser(request,response,['admin','superadmin']);if(user)return json(response,200,all('SELECT st.*,p.name product_name,u.name admin_name FROM stock_transactions st JOIN products p ON p.id=st.product_id JOIN users u ON u.id=st.admin_id ORDER BY st.created_at DESC LIMIT 100'));return;}
  if(path==='/api/admin/coupons' && request.method==='GET'){const user=requireUser(request,response,['superadmin']);if(user)return json(response,200,all('SELECT * FROM coupons ORDER BY created_at DESC'));return;}
  if(path==='/api/admin/coupons' && request.method==='POST'){const user=requireUser(request,response,['superadmin']);if(!user)return;const data=await body(request);const code=String(data.code||'').trim().toUpperCase();if(!/^[A-Z0-9_-]{3,24}$/.test(code)||!['percent','fixed'].includes(data.type)||!Number.isInteger(Number(data.value))||Number(data.value)<1)return error(response,400,'Enter a valid coupon.');if(data.type==='percent'&&Number(data.value)>100)return error(response,400,'Percentage cannot exceed 100.');try{const couponId=id();run('INSERT INTO coupons VALUES (?,?,?,?,?,?,?,?,?,?)',couponId,code,data.type,Number(data.value),Number(data.minimumCents||0),data.startsAt||null,data.endsAt||null,data.usesRemaining===''||data.usesRemaining==null?null:Number(data.usesRemaining),1,now());return json(response,201,{id:couponId});}catch{return error(response,409,'That coupon code already exists.');}}
  if(path==='/api/admin/users' && request.method==='GET'){const user=requireUser(request,response,['superadmin']);if(user)return json(response,200,all('SELECT id,name,email,role,active,created_at FROM users ORDER BY created_at DESC'));return;}
  if(path==='/api/admin/users' && request.method==='POST'){const user=requireUser(request,response,['superadmin']);if(!user)return;const data=await body(request);if(!data.name?.trim()||!/^\S+@\S+\.\S+$/.test(data.email||'')||String(data.password||'').length<10||String(data.password||'').length>1024||!['admin','superadmin'].includes(data.role))return error(response,400,'Enter a name, email, role, and password of at least 10 characters.');if(data.role==='superadmin'&&user.role!=='superadmin')return error(response,403,'Only a super admin can create this role.');try{const userId=id();run('INSERT INTO users VALUES (?,?,?,?,?,?,?)',userId,data.name.trim(),data.email.trim().toLowerCase(),hashPassword(data.password),data.role,1,now());return json(response,201,{id:userId});}catch{return error(response,409,'That email is already registered.');}}
  if(path==='/api/admin/settings' && request.method==='GET'){const user=requireUser(request,response,['superadmin']);if(user)return json(response,200,config);return;}
  if(path==='/api/admin/store-photos' && request.method==='GET'){const user=requireUser(request,response,['admin','superadmin']);if(user)return json(response,200,all('SELECT sp.*,u.name admin_name FROM store_photos sp JOIN users u ON u.id=sp.admin_id ORDER BY sp.created_at DESC'));return;}
  if(path==='/api/admin/store-photos' && request.method==='POST'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;const data=await body(request);if(!String(data.url||'').startsWith('/uploads/')||!['hero','gallery'].includes(data.placement))return error(response,400,'Choose an uploaded image and a valid placement.');const photoId=id();run('INSERT INTO store_photos VALUES (?,?,?,?,?,?)',photoId,data.url,data.placement,String(data.caption||'').slice(0,120),user.id,now());return json(response,201,{id:photoId});}
  if(path.match(/^\/api\/admin\/store-photos\/[a-f0-9]+$/) && request.method==='DELETE'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;run('DELETE FROM store_photos WHERE id=?',path.split('/').pop());return json(response,200,{ok:true});}
  if(path==='/api/admin/upload' && request.method==='POST'){const user=requireUser(request,response,['admin','superadmin']);if(!user)return;const data=await body(request,5_500_000);const match=String(data.dataUrl||'').match(/^data:(image\/(png|jpeg|webp));base64,([A-Za-z0-9+/=]+)$/);if(!match)return error(response,400,'Upload a PNG, JPEG, or WebP image.');const bytes=Buffer.from(match[3],'base64');if(bytes.length>4_000_000)return error(response,400,'Image must be 4 MB or smaller.');const valid=match[2]==='png'?bytes.subarray(0,8).equals(Buffer.from('89504e470d0a1a0a','hex')):match[2]==='jpeg'?bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff:bytes.subarray(0,4).toString()==='RIFF'&&bytes.subarray(8,12).toString()==='WEBP';if(!valid)return error(response,400,'Image content does not match its file type.');const file=`${id()}.${match[2]==='jpeg'?'jpg':match[2]}`;await writeFile(join(root,'uploads',file),bytes,{flag:'wx'});return json(response,201,{url:`/uploads/${file}`});}
  return serveFile(response,path);
}catch(e){console.error(e);return error(response,e.status||400,e.status?e.message:'Request failed.');}});
server.requestTimeout=30_000;server.headersTimeout=10_000;server.keepAliveTimeout=5_000;server.maxHeadersCount=100;
server.listen(port,()=>console.log(`Sports World running at http://localhost:${port}`));
